# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='id',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='obj_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
